// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxghvgqewrozsyotlyqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54Z2h2Z3Fld3JvenN5b3RseXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjUwNjcsImV4cCI6MjA3MjE0MTA2N30.FTRzNv-E_vSdkWuYsmY-MZ_byQq4zKkugBOmj4JTEpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});